version: '3'

services:

  db:
    image: sastix/cmsmariadb:1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sastixcms
      MYSQL_PASSWORD: sastixcms
      MYSQL_USER: sastixcms
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: